alias rb := remote-build
alias rm := rm-g5k-nfs-store
alias g := get-g5k-nfs-store
alias o := oarsub
alias k := kareboot
alias u := generate-user-nix
alias fmt := format

default:
    @just --list

# Build g5k-image on nix-datamove
remote-build JSON_FILE="result.json":
    nix --extra-experimental-features mounted-ssh-store --store mounted-ssh-ng://doozer@nix-datamove build .#g5k-nfs-store --no-link --json > {{ JSON_FILE }}

# Remove g5k-image directory
rm-g5k-nfs-store:
    #!/usr/bin/env bash
    chmod -R 755 kernel initrd
    rm -f kernel initrd init-path

# Retrieve g5k-image files from remote builder
get-g5k-nfs-store:
    #!/usr/bin/env bash
    nix_store_g5k_nfs_store=$(jq -r .[0].outputs.out result.json)
    if [ -f kernel ]; then
        echo "remove previous g5k-nfs-store stuff"
        just rm-g5k-nfs-store
    fi
        scp -r doozer@nix-datamove:$nix_store_g5k_nfs_store/kernel .
        scp -r doozer@nix-datamove:$nix_store_g5k_nfs_store/initrd .
        echo "$nix_store_g5k_nfs_store/init" > init-path
    just update-init-kareboot-yml

# Generate the user.nix file
generate-user-nix:
    #!/usr/bin/env bash
    echo '{
        name = "'$(id -nu)'";
        uid = '$(id -u)';
        id_rsa_pub = "'$(cat ~/.ssh/id_rsa.pub)'";
    }' > user.nix

# Submit interactive job, 1 node, with deploy and destructive types
oarsub OPTIONS="":
    oarsub {{ OPTIONS }} -t deploy -t destructive -l nodes=1 -I

# Deploy with kareboot
kareboot:
    kareboot3 simple --custom-steps g5k-nfs-store-kexec-reboot.yml -m $(head -n 1 $OAR_NODEFILE)

update-init-kareboot-yml:
    #!/usr/bin/env bash
    init_path=$(cat init-path)
    sed -i "s|\\binit=[^ ]*|init=$init_path|"  g5k-nfs-store-kexec-reboot.yml

# Format files: nix, README.md, justfile
[group('chore')]
format:
    nix fmt
